services:
  php:
          image: php:fpm
          volumes:
            - ./code:/code
  nginx:
          image: nginx:latest
          ports:
            - 8000:80
          volumes:
            - ./site.conf:/etc/nginx/conf.d/site.conf
            - ./code:/code