version: '3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile_python
        ports:
          - '8000:8000'
        volumes:
            - ./app:/app/
        command: bash /app/start_python.sh

    tailwind:
        build:
            context: .
            dockerfile: Dockerfile_npm
        volumes:
            - ./app:/app/
        command: bash /app/start_npm.sh
        tty: true
        stdin_open: true # https://github.com/rails/rails/issues/44048
        depends_on:
            - web