version: '3.1'

services:
    db:
        image: mariadb
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: rootpw
            MYSQL_DATABASE: mydb
            MYSQL_USER: mysqluser
            MYSQL_PASSWORD: mysqlpw

        volumes:
            - ./init:/docker-entrypoint-initdb.d

    adminer:
        image: adminer
        restart: always
        ports:
            - 8888:8080