version: '3.8'

services:
  ftp_server:
    image: delfer/alpine-ftp-server
    container_name: ftp-server
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:$FTP_PATH
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    # user: "$FTP_UID:$FTP_GID"